### ISSUE TITLE
[Version 1.2.1] リツイート画面でのアカウント切り替えの動作

### ISSUE THREAD

**Issue by homomaid** [chitoku-k/TweetDeckAccountsSwitcher#1]
1.2.1 のバージョンにて、リツイート画面にてアカウントを変更する際に、
「元のアカウントを指定している状態 → 何もアカウントを指定していない状態 → 変更していないアカウントを指定している状態」
という動作を確認いたしました。
なお、「→」記号は、変更したいアカウントのアイコンをクリックする動作を意味しています。

「元のアカウントを指定している状態 → 変更していないアカウントを指定している状態」
と動作するとより使いやすくなると思います…！

**Comment by chitoku-k** [comment]
@homomaid 
ご報告ありがとうございます！ こちらでは再現できませんでした。
環境と具体的な再現手順をお書きください。

例）
1. アカウントが 1 つ選択されている状態で別のアカウントを選択する
2. 1 で選択したアカウントと元から選択されていたアカウントの両方が選択された状態になる

環境
Chrome 58.0.3004.3
macOS 10.12.3

**Comment by homomaid** [comment]
@chitoku-k 
お書きいたしましたので、ご確認ください！

### 再現までの手順
TweetDeck にはアカウント A, B が登録されているとします。

1. アカウントが 1 つ選択されている状態(from A)で、別のアカウントを選択する
2. A, B のどちらのアカウントも選択されていない状態(from )となる
3. その後、A, B のいずれを選択した場合にも、正しくそのアカウントが選択された状態になる

### 環境
- Chrome 57.0.2987.37 beta (64-bit)
- macOS 10.12.3

**Comment by chitoku-k** [comment]
@homomaid 
ありがとうございます。以下の環境でも再現しないようでした。

1. アカウントが 1 つ選択されている状態で、別のアカウントを選択する
2. 1 で選択したアカウントだけが選択される状態になる

環境
Chrome 57.0.2970.0
Windows 7 (64bit)

**Comment by chitoku-k** [comment]
`dataColumnsLoaded` が複数回呼び出される環境があるようです。

https://github.com/chitoku-k/TweetDeckAccountsSwitcher/blob/727a01f58b7d16f99b670fc038ae26b5b505f715/extension.js#L57
